apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: coffees.cache.anish.com
spec:
  group: cache.anish.com
  names:
    kind: coffee
    plural: coffees
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                size:
                  type: integer
              type: object
            status:
              properties:
                nodes:
                  items:
                    type: string
                  type: array
              type: object
          type: object
      subresources:
        status: {}
              
